### PR TITLE
Twilio Serverless services automatic deployment with terraform

### PR DESCRIPTION
**Pull request by lvaladares**
### Summary

_Provide a summary of the change_

### Checklist

- [ ] Tested changes end to end
- [ ] Updated documentation
- [ ] Requested one or more reviewers

### CODE REVIEW

**Review by ChrisAmora — APPROVED** [review]

**Review by jhunter-twilio — CHANGES_REQUESTED** [review]
Screenshot 2023-09-20 at 13 15 01

Looks like some paths are not aligned here.

Really excited to get this change in but i also want to sanity check how we reference the function resources - currently we use the CLI and inject via the action.yaml.  If we can remove that need for functions that would be great.

**Comment by lvaladares** [comment]
Let me check that @jhunter-twilio. Any idea how can I trigger the pipelines for a dry/test run? actions are a bit finicky because it needs the commit to check if it's working 😢

**Comment by ChrisAmora** [comment]
> Let me check that @jhunter-twilio. Any idea how can I trigger the pipelines for a dry/test run? actions are a bit finicky because it needs the commit to check if it's working 😢 🐔 🥚

One way would be to fork the template and populate with your Twilio the environment variables.

**Comment by lvaladares** [comment]
services folder was missing because git doesn't commit empty folders

**Comment by lvaladares** [comment]
will close this and open a new pr from another fork

**Comment by lvaladares** [comment]
moved to -> [](https://github.com/twilio-professional-services/flex-project-template/pull/366)

**Pull request closed without merging**
