### PR TITLE
New approach for internal-call feature

### PR DESCRIPTION
**Pull request by dremin**
### Summary

Completely new approach to the internal-call feature, allowing TaskRouter to orchestrate the conference natively. This addresses issues with the previous approach:
- Internal transfers now work
- External transfers are shown correctly in UI
- Dual-channel recording now works (without code from #97)
- Pause recording now works
- Flex error no longer needs to be suppressed (#96)
- A single task is reported in Flex Insights
- Can be used when running the template locally

The new approach is simple: Call a "dummy" phone number or SIP address (which immediately disconnects, but does not end the conference) and automatically warm transfer to the desired agent.

### Checklist
- [x] Tested changes end to end
- [x] Any Flex config changes added to all environment files
- [x] Completed README template for new features
  - [x] Feature summary - _high level summary of what the feature does_
  - [x] Flex User Experience with animations - _animations with descriptions if necessary of the user experience in Flex_
  - [x] Setup and dependencies - _description of any setup steps required for this feature_
  - [x] How does it work? - _description of plumbing supporting feature_
- [ ] Updated build number in package.json when modifying a flex plugin
- [x] Added PR Label "ready-for-review"
- [x] Requested one or more reviewers for the PR

### CODE REVIEW

**Comment by dremin** [comment]
Still going to pursue this, merging the other fixes for the current approach to allow more time to mature this approach.

**Comment by dremin** [comment]
The current issue with this approach is that it incurs additional cost compared to the previous approach by using a phone number. Attempts to implement this approach without adding cost have not been successful so far.

**Comment by dremin** [comment]
Abandoning this PR; a true long-term solution needs to come from the product level to avoid the issues with this PR.

**Comment by jared-hunter** [comment]
So many dashed hopes!

**Pull request closed without merging**
