### PR TITLE
Add programmable chat transfer for 2.0

### PR DESCRIPTION
**Pull request by dremin**
### Summary
We already have CBM chat transfer, but customers migrating from 1.x to 2.0 will likely still be running programmable chat when they upgrade, so this feature fills that gap. This is brought over from 1.x unchanged except for break-fixes (not much point in putting significant effort into deprecated functionality). Also updated the video button to match the transfer button style.

The new CBM transfer feature has been renamed to `conversation-transfer` and this feature takes the `chat-transfer` name to allow easy migration from the 1.x feature.

I also fixed some bugs outside of the feature that I ran into while regression testing:
- Fixed update-task-attributes saving null values
- Fixed chat-transfer sending null string to complete-task-for-transfer
- Fixed conversation-transfer when running locally

### Checklist
- [x] Tested changes end to end
- [x] Any Flex config changes added to all environment files
- [x] For Flex features added, ensure the feature list on the README on the project root folder is updated
- [x] For Flex v2 features, ensured pluginsLoaded event handler is added 
- [x] Completed README template for new features
  - [x] Feature summary - _high level summary of what the feature does_
  - [x] Flex User Experience with animations - _animations with descriptions if necessary of the user experience in Flex_
  - [x] Setup and dependencies - _description of any setup steps required for this feature_
  - [x] How does it work? - _description of plumbing supporting feature_
- [x] Updated build number in package.json when modifying a flex plugin
- [x] Added PR Label "ready-for-review"
- [x] Requested one or more reviewers for the PR

### CODE REVIEW

**Comment by jhunter-twilio** [comment]
Yeah I think I like the last option the best too. Although it might be easier to complete after finalizing the review of multi participant chat.

**Comment by johnfischelli** [comment]
Might I propose `Flex Programmable Chat Transfer` or alternatively `Legacy Chat Transfer` and `Flex Conversations Transfer`? I'm not sure any customers speak in terms of `cbm` specifically. Additionally, our docs refer to `Flex Conversations` https://www.twilio.com/docs/flex/conversations so I feel like this is how customers will think about it and the language they will use.

**Comment by johnfischelli** [comment]
ahhh after looking at the code I see the Flex UI literally has a TaskHelper method `isCBMTask` - so maybe that language is ok - though its super confusing it does not match our docs.

**Comment by dremin** [comment]
> Yeah I think I like the last option the best too. Although it might be easier to complete after finalizing the review of multi participant chat.

Good point, I'll keep this parked until that one is merged.

**Comment by dremin** [comment]
While testing, I found an existing issue where error messages from the create-transfer-task function do not get sent to the frontend. Per the original message in the PR, I'm going to leave the issue as-is for now; we can always revisit if it looks like prog chat will stick around for some reason.

**Review by dahamilton-twilio — APPROVED** [review]
looks good to me

**Pull request merged**
