### PR TITLE
Add template docs site

### PR DESCRIPTION
**Pull request by mschmitt19**
### Summary

This (large) PR introduces a new approach to documentation by adding in the `docs` root level directory and the `serverless-docs` Twilio Function & Asset to host the documentation site (located [here](https://flex-project-template-docs-2618-dev.twil.io/index.html)).

- Each feature-level README has been trimmed down to point to the documentation site, and a new section was added towards the top of the main README to point towards the documentation site.
- The `pull-request-template.md` was updated to reflect the new documentation procedures and adding content to the documentation site
- A Github Actions workflow was added to build and deploy the site to Twilio Assets, which will be triggered on each new merge into the `main` branch.

### CODE REVIEW

**Comment by jhunter-twilio** [comment]
This looks super cool, I've not done a comprehensive review but just one question I'm asking myself is whether there should still be a readme per feature that just points to the docs rather than just blowing them away. I could see that getting tedious

**Comment by mschmitt19** [comment]
> 

@jhunter-twilio Sam and I were actually just discussing this -- we leaned towards just removing them completely from the feature level folders and having the feature docs exclusively in the docs site; I originally just linked out to the docs site in each feature readme, so can revert to that if we think that's the best path forward.

**Comment by dremin** [comment]
This is looking wicked good!

Things we can address in follow-ups:
- Remove positioning/numbering from feature readmes (use auto alphabetical sorting to allow for easy feature adding)
- Determine what to do with per-package readmes. Options:
  - No readme in package
  - Stub readme in package pointing to docs site (my preference!)
  - Automatically copy the readme to the other location
- Further organizational enhancements as we see fit

**Comment by jhunter-twilio** [comment]
This is a huge upgrade, fantastic work @mschmitt19

**Review by dremin — APPROVED** [review]
🎉

**Pull request merged**
